/**
 * Generate a draft fix PR for a finding.
 * Always creates as draft=true — no merge path exists (FR-6).
 * Requires GitHub App to have pull_requests:write + contents:write scopes.
 */
import { createSign } from "crypto";
import pool from "./db";

interface Finding {
  id: string;
  tenant_id: string;
  title: string;
  type: string;
  severity: string;
  asset: string;
  rule_id: string | null;
  raw: unknown;
  connector_id: string;
}

async function githubJWT(): Promise<string> {
  const appId = process.env.GITHUB_APP_ID!;
  const pem = process.env.GITHUB_APP_PRIVATE_KEY!.replace(/\\n/g, "\n");
  const now = Math.floor(Date.now() / 1000);
  const header = Buffer.from(JSON.stringify({ alg: "RS256", typ: "JWT" })).toString("base64url");
  const payload = Buffer.from(JSON.stringify({ iat: now - 60, exp: now + 600, iss: appId })).toString("base64url");
  const unsigned = `${header}.${payload}`;
  const sign = createSign("RSA-SHA256");
  sign.update(unsigned);
  const sig = sign.sign(pem, "base64url");
  return `${unsigned}.${sig}`;
}

async function getInstallationToken(installationId: string): Promise<string> {
  const jwt = await githubJWT();
  const resp = await fetch(
    `https://api.github.com/app/installations/${installationId}/access_tokens`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${jwt}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
    }
  );
  if (!resp.ok) throw new Error(`GitHub token exchange failed: ${resp.status}`);
  const data = await resp.json();
  return data.token;
}

export async function createFixPR(finding: Finding): Promise<{ pr_url: string; pr_number: number }> {
  // Get installation_id from connector
  const { rows } = await pool.query(
    "SELECT credential_ref FROM connectors WHERE id = $1 AND revoked_at IS NULL",
    [finding.connector_id]
  );
  if (!rows[0]) throw new Error("Connector not found or revoked");

  const token = await getInstallationToken(rows[0].credential_ref);

  // Derive repo from asset: first two path segments are owner/repo
  const parts = finding.asset.split("/");
  const repoFullName = `${parts[0]}/${parts[1]}`;

  // Get default branch
  const repoResp = await fetch(`https://api.github.com/repos/${repoFullName}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json" },
  });
  if (!repoResp.ok) throw new Error(`Could not fetch repo: ${repoResp.status}`);
  const repoData = await repoResp.json();
  const defaultBranch = repoData.default_branch ?? "main";

  // Create a branch for the fix
  const branchName = `sentinel8/fix-${finding.id.slice(0, 8)}`;
  const refResp = await fetch(`https://api.github.com/repos/${repoFullName}/git/ref/heads/${defaultBranch}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json" },
  });
  if (!refResp.ok) throw new Error(`Could not get base ref: ${refResp.status}`);
  const refData = await refResp.json();
  const sha = refData.object.sha;

  const createBranch = await fetch(`https://api.github.com/repos/${repoFullName}/git/refs`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha }),
  });
  if (!createBranch.ok && createBranch.status !== 422) {
    throw new Error(`Could not create branch: ${createBranch.status}`);
  }

  // Create the PR as draft — no merge path (FR-6)
  const prBody = `## AI-generated fix suggestion ⚠️ Human review required

**Finding:** ${finding.title}
**Severity:** ${finding.severity}
**Type:** ${finding.type}
**Asset:** \`${finding.asset}\`
**Rule:** ${finding.rule_id ?? "—"}
**Finding ID:** ${finding.id}

---

This PR was generated by Sentinel8 as a draft fix suggestion.
**It must be reviewed and approved by a human before merging.**
Auto-merge is disabled. See [Sentinel8 dashboard](/dashboard) for full context.

> AI-generated, human-reviewed — do not merge without security review.`;

  const prResp = await fetch(`https://api.github.com/repos/${repoFullName}/pulls`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title: `[Sentinel8] Fix: ${finding.title.slice(0, 100)}`,
      body: prBody,
      head: branchName,
      base: defaultBranch,
      draft: true,  // FR-6: always draft, never auto-merge
    }),
  });
  if (!prResp.ok) {
    const err = await prResp.text();
    throw new Error(`Could not create PR: ${prResp.status} ${err.slice(0, 200)}`);
  }
  const pr = await prResp.json();

  // Persist PR reference on the finding
  await pool.query(
    "UPDATE findings SET fix_pr_url = $1, fix_pr_number = $2 WHERE id = $3",
    [pr.html_url, pr.number, finding.id]
  );

  return { pr_url: pr.html_url, pr_number: pr.number };
}
