import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";

export interface ScanFinding {
  severity: string;
  scanner: string;
  type: string;
  title: string;
  rule_id: string;
  asset: string;
}

export interface ScanReport {
  repo: string;
  counts: { critical: number; high: number; medium: number; low: number; total: number };
  findings: ScanFinding[];
  completedAt: string | null;
}

const SEV_COLOR: Record<string, string> = {
  critical: "#DC2626", high: "#EA580C", medium: "#CA8A04", low: "#16A34A",
};

const s = StyleSheet.create({
  page: { padding: 40, fontSize: 10, color: "#1E293B", fontFamily: "Helvetica" },
  h1: { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 2 },
  repo: { fontSize: 12, color: "#475569", marginBottom: 2 },
  meta: { fontSize: 9, color: "#94A3B8", marginBottom: 18 },
  tiles: { flexDirection: "row", gap: 8, marginBottom: 22 },
  tile: { flex: 1, padding: 10, borderRadius: 4, border: "1 solid #E2E8F0" },
  tileNum: { fontSize: 22, fontFamily: "Helvetica-Bold" },
  tileLabel: { fontSize: 8, color: "#64748B", marginTop: 2 },
  sectionTitle: { fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 8 },
  row: { flexDirection: "row", paddingVertical: 5, borderBottom: "0.5 solid #E2E8F0" },
  sev: { width: 50, fontFamily: "Helvetica-Bold" },
  title: { flex: 1, paddingRight: 8 },
  asset: { width: 150, color: "#64748B", fontSize: 8 },
  scanner: { width: 50, color: "#94A3B8", fontSize: 8, textAlign: "right" },
  headRow: { flexDirection: "row", paddingBottom: 5, borderBottom: "1 solid #CBD5E1" },
  headCell: { fontFamily: "Helvetica-Bold", fontSize: 8, color: "#64748B" },
  footer: { position: "absolute", bottom: 24, left: 40, right: 40, fontSize: 8, color: "#94A3B8", textAlign: "center" },
});

function ReportDoc({ report }: { report: ScanReport }) {
  const { repo, counts, findings } = report;
  return (
    <Document>
      <Page size="A4" style={s.page} wrap>
        <Text style={s.h1}>Security Scan Report</Text>
        <Text style={s.repo}>{repo}</Text>
        <Text style={s.meta}>
          Generated by Sentinel8 · {report.completedAt ? new Date(report.completedAt).toLocaleString() : ""} · Trivy + Semgrep + Gitleaks
        </Text>

        <View style={s.tiles}>
          {(["critical", "high", "medium", "low"] as const).map((k) => (
            <View key={k} style={s.tile}>
              <Text style={[s.tileNum, { color: SEV_COLOR[k] }]}>{counts[k]}</Text>
              <Text style={s.tileLabel}>{k.toUpperCase()}</Text>
            </View>
          ))}
        </View>

        <Text style={s.sectionTitle}>All findings ({counts.total})</Text>

        <View style={s.headRow}>
          <Text style={[s.headCell, { width: 50 }]}>SEV</Text>
          <Text style={[s.headCell, { flex: 1 }]}>FINDING</Text>
          <Text style={[s.headCell, { width: 150 }]}>LOCATION</Text>
          <Text style={[s.headCell, { width: 50, textAlign: "right" }]}>SCANNER</Text>
        </View>

        {findings.length === 0 ? (
          <Text style={{ marginTop: 10, color: "#16A34A" }}>No findings — this repo looks clean.</Text>
        ) : (
          findings.map((f, i) => (
            <View key={i} style={s.row} wrap={false}>
              <Text style={[s.sev, { color: SEV_COLOR[f.severity] ?? "#64748B" }]}>
                {f.severity.toUpperCase()}
              </Text>
              <Text style={s.title}>{f.title}</Text>
              <Text style={s.asset}>{f.asset}</Text>
              <Text style={s.scanner}>{f.scanner}</Text>
            </View>
          ))
        )}

        <Text style={s.footer} fixed>
          Sentinel8 free scan · findings are location-only and contain no secret values
        </Text>
      </Page>
    </Document>
  );
}

/** Build the PDF and trigger a browser download. Client-side only. */
export async function downloadScanPdf(report: ScanReport): Promise<void> {
  const blob = await pdf(<ReportDoc report={report} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `sentinel8-scan-${report.repo.replace("/", "-")}.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
